### ISSUE TITLE
Setting a winrm port in knife.rb breaks linux bootstrapping

### ISSUE THREAD

**Issue by troyready** [chef-partners/knife-vsphere#178]
I've been using the new windows cloning (which is awesome!), so I defined `knife[:winrm_user], knife[:winrm_transport], & knife[:winrm_port]` in my knife.rb.

Now though when I attempt to clone a linux VM, the bootstrap process is attempting to connect to winrm on the VM (specifically to the winrm port specified in my config file) and failing. This behavior doesn't change when I specify a SSH port on the command line.

Is there a way I can override this without removing those settings from my knife config?

**Comment by swalberg** [comment]
Does `--bootstrap_protocol ssh` get you anywhere?

**Comment by troyready** [comment]
Should have mentioned - no, it still produced the same error.

**Comment by mheidenr** [comment]
@troyready can you please provide more information (the command and its output)?

**Comment by troyready** [comment]
Sure; here are 3 (failed) attempts at cloning and bootstrapping a VM (in attempts 2 & 3 I tried adding SSH options):

```
Attempt #1:
troyready@myworkstation:~$ knife vsphere vm clone mylinuxsystem --template "Ubuntu1404" --folder "Templates" --dest-folder "Templates" --datastore SAN_MyDatastore --resource-pool "VM Cluster/Dev" --cips 192.168.0.25/24 --cgw 192.168.0.1 --cvlan Internal_Vlan --cdnsips 192.168.0.2 --cspec linuxserverprod --start --bootstrap true --ssh-user bootstrapuser --environment staging --run-list "role[base_role]" -N mylinuxsystem.ourorg.com --cdomain ourorg.com --chostname mylinuxsystem --cram 3 --ccpu 2
Cloning template Ubuntu1404 to new VM mylinuxsystem
Finished creating virtual machine mylinuxsystem
Powered on virtual machine mylinuxsystem

Waiting for sshd access to become availabledone
Doing old-style registration with the validation key at /home/troyready/.chef/ourorg-validator.pem...
Delete your validation key in order to use your user credentials instead

Connecting to 192.168.0.25
ERROR: Network Error: Connection refused - connect(2) for "192.168.0.25" port 5986
Check your knife configuration and network settings


Attempt #2:
troyready@myworkstation:~$ knife vsphere vm clone mylinuxsystem --template "Ubuntu1404" --folder "Templates" --dest-folder "Templates" --datastore SAN_MyDatastore --resource-pool "VM Cluster/Dev" --cips 192.168.0.25/24 --cgw 192.168.0.1 --cvlan Internal_Vlan --cdnsips 192.168.0.2 --cspec linuxserverprod --start --bootstrap true --ssh-user bootstrapuser --environment staging --run-list "role[base_role]" -N mylinuxsystem.ourorg.com --cdomain ourorg.com --chostname mylinuxsystem --cram 3 --ccpu 2 --ssh-port 22
Cloning template Ubuntu1404 to new VM mylinuxsystem
Finished creating virtual machine mylinuxsystem
Powered on virtual machine mylinuxsystem

Waiting for sshd access to become availabledone
Doing old-style registration with the validation key at /home/troyready/.chef/ourorg-validator.pem...
Delete your validation key in order to use your user credentials instead

Connecting to 192.168.0.25
ERROR: Network Error: Connection refused - connect(2) for "192.168.0.25" port 5986
Check your knife configuration and network settings

Attempt #3:
troyready@myworkstation:~$ knife vsphere vm clone mylinuxsystem --template "Ubuntu1404" --folder "Templates" --dest-folder "Templates" --datastore SAN_MyDatastore --resource-pool "VM Cluster/Dev" --cips 192.168.0.25/24 --cgw 192.168.0.1 --cvlan Internal_Vlan --cdnsips 192.168.0.2 --cspec linuxserverprod --start --bootstrap true --ssh-user bootstrapuser --environment staging --run-list "role[base_role]" -N mylinuxsystem.ourorg.com --cdomain ourorg.com --chostname mylinuxsystem --cram 3 --ccpu 2 --ssh-port 22 --bootstrap-protocol ssh
Cloning template Ubuntu1404 to new VM mylinuxsystem
Finished creating virtual machine mylinuxsystem
Powered on virtual machine mylinuxsystem

Waiting for sshd access to become availabledone
Doing old-style registration with the validation key at /home/troyready/.chef/ourorg-validator.pem...
Delete your validation key in order to use your user credentials instead

Connecting to 192.168.0.25
ERROR: Network Error: Connection refused - connect(2) for "192.168.0.25" port 5986
Check your knife configuration and network settings
```

**Comment by tim95030** [comment]
Add ssh_user and more importantly ssh_port in either the command or your knife.rb.

If you do not declare bootstrap protocol it will use ssh on Linux by default what is happening is you don't have ssh_port defined so it's using the winrn_port. I grabbed that magic from knife ec2 I can remove it if that's what people want. Currently though if you set the ssh_port you should be good to go.

**Comment by troyready** [comment]
@tim95030 See my third attempt above -- I set both and got the same result.

**Comment by tim95030** [comment]
Looking at the code deeper I see the issue. I need to find out why knife-ec2 has this method so I can better understand it, but the logic of it is that if you define the winrm_port then it will override the ssh_port to that unless ssh_port is defined to something that is not it's default. This is what is causing your issue setting ssh_port to 22 is the default, so the winrm port is overriding that. Are you using a non-standard winrm port? If you aren't simply remove that setting from knife config and you should be set for both windows and linux. In the meantime I will figure out why this is there and see if we can do anything about it or if it is there to solve another issue.

**Comment by tim95030** [comment]
So the code is there so that you can use -x for user, -p for port, and -P for password for either ssh_user, ssh_port, and ssh_password or for winrm_user, winrm_port, and winrm_password.

We inherit winrm settings from knife windows and the ssh portion comes from us. The short of it is if you put those settings in your knife.rb and don't use a non-default ssh port it will override the port. Which is the issue you are seeing. 

This all being said the workaround is remove the setting from knife.rb and the fix is undetermined at this point. I will have to think on that some.

**Comment by troyready** [comment]
Appreciate it. We're using ssl on port 5986 for winrm, which seems to be the standard for ssl but not the default IIRC.

**Comment by tim95030** [comment]
Use this then:   winrm_transport = ssl in your knife config and remove the port definition

**Comment by troyready** [comment]
Just updated knife-windows and removed the port definition. It fixed linux bootstrapping, but winrm still seems to be attempting to connect to port 5985 (or at least that's what it's reporting):

```
troyready@myworkstation:~$ knife vsphere vm clone mywsystem --ccpu 2 --cdomain ourorg.com --cgw 192.168.0.1 --chostname mywsystem --cips 192.168.0.25/24 --cdnsips 192.168.0.2 --cram 3 --cspec Win2012R2Data --cvlan Internal_Vlan --datastore SAN_MyDatastore --dest-folder Templates --folder Templates --start --resource-pool 'VM Cluster/Dev' --template Win2012R2Data --bootstrap --bootstrap-protocol winrm --ca-trust-file ourorg_cert.pem -N mywsystem.ad.ourorg.com -r 'role[base_role]' -x 'troyready@ad.ourorg.com' -P 'MyPassword123'
Cloning template Win2012R2Data to new VM mywsystem
Finished creating virtual machine mywsystem
Powered on virtual machine mywsystem
Waiting for customization to complete...
Waiting for sysprep..............
Customization of VM mywsystem succeeded. Customization log located at C:\Windows\TEMP\vmware-imc\guestcust.log in the guest OS.
Customization Complete

Waiting for winrm access to become availableERROR: Errno::EINVAL: Invalid argument - connect(2) for "IPV6ADDRESSHERE" port 5985
```

**Comment by tim95030** [comment]
What version of knife-windows are you using?

**Comment by troyready** [comment]
My knife-windows version is 0.8.5 (I updated before my last comment); from what I can tell it's not being pinned back by appbundler or anything in my ChefDK setup (though I could be wrong on that).

Here's my attempt at cloning today with debug output:

```
troyready@myworkstation:~$ knife vsphere vm clone mywsystem --ccpu 2 --cdomain ourorg.com --cgw 192.168.0.1 --chostname mywsystem --cips 192.168.0.25/24 --cdnsips 192.168.0.2 --cram 3 --cspec Win2012R2Data --cvlan Internal_Vlan --datastore SAN_MyDatastore --dest-folder Templates --folder Templates --start --resource-pool 'VM Cluster/Dev' --template Win2012R2Data --bootstrap --bootstrap-protocol winrm --ca-trust-file ourorg_cert.pem -N mywsystem.ad.ourorg.com -r 'role[base_role]' -x 'troyready@ad.ourorg.com' -P 'MyPassword123' -VV
INFO: Using configuration from /home/troyready/.chef/knife.rb
DEBUG: value for config item chef_node_name: mywsystem.ourorg.com
DEBUG: value for config item vsphere_host: vsphere.ourorg.com
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl: 
DEBUG: value for config item vsphere_user: troyready@ad.ourorg.com
DEBUG: value for config item vsphere_pass: base64:MYPASSHASH
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host: 
DEBUG: value for config item proxy_port: 
DEBUG: value for config item vsphere_dc: OurOrg Virtual Datacenter
DEBUG: value for config item folder: Templates
DEBUG: value for config item vsphere_dc: OurOrg Virtual Datacenter
DEBUG: value for config item linked_clone: 
DEBUG: value for config item resource_pool: VM Cluster/Dev
DEBUG: value for config item resource_pool: VM Cluster/Dev
DEBUG: value for config item vsphere_dc: OurOrg Virtual Datacenter
DEBUG: value for config item linked_clone: 
DEBUG: value for config item datastore: SAN_MyDatastore
DEBUG: value for config item datastorecluster: 
DEBUG: value for config item datastore: SAN_MyDatastore
DEBUG: value for config item datastore: SAN_MyDatastore
DEBUG: value for config item vsphere_dc: OurOrg Virtual Datacenter
DEBUG: value for config item datastorecluster: 
DEBUG: value for config item thin_provision: 
DEBUG: value for config item mark_as_template: 
DEBUG: value for config item annotation: 
DEBUG: value for config item customization_cpucount: 2
DEBUG: value for config item customization_cpucount: 2
DEBUG: value for config item customization_memory: 3
DEBUG: value for config item customization_memory: 3
DEBUG: value for config item customization_vlan: Internal_Vlan
DEBUG: value for config item customization_vlan: Internal_Vlan
DEBUG: value for config item vsphere_dc: OurOrg Virtual Datacenter
DEBUG: value for config item customization_spec: Win2012R2Data
DEBUG: value for config item customization_spec: Win2012R2Data
DEBUG: value for config item customization_dns_ips: 192.168.0.2
DEBUG: value for config item customization_dns_ips: 192.168.0.2
DEBUG: value for config item customization_dns_suffixes: 
DEBUG: value for config item customization_gw: 192.168.0.1
DEBUG: value for config item customization_gw: 192.168.0.1
DEBUG: value for config item disable_customization: 
DEBUG: Identified os as windows.
DEBUG: value for config item customization_plugin: 
DEBUG: value for config item vsphere_dc: OurOrg Virtual Datacenter
Cloning template Win2012R2Data to new VM mywsystem
Finished creating virtual machine mywsystem
DEBUG: value for config item customization_plugin: 
DEBUG: value for config item mark_as_template: 
DEBUG: value for config item power: true
Powered on virtual machine mywsystem
DEBUG: value for config item bootstrap: true
DEBUG: Connect Host for Bootstrap: fd12:3456:789a:1::1
DEBUG: value for config item ssh_port: 22
DEBUG: value for config item bootstrap_protocol: winrm
DEBUG: Identified os as windows.
Waiting for customization to complete...
DEBUG: value for config item sysprep_timeout: 600
Waiting for sysprep................
Customization of VM mywsystem succeeded. Customization log located at C:\Windows\TEMP\vmware-imc\guestcust.log in the guest OS.
Customization Complete
DEBUG: value for config item fqdn: fd12:3456:789a:1::1
DEBUG: value for config item winrm_port: 5985

Waiting for winrm access to become available/home/troyready/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.3/lib/chef/knife/vsphere_vm_clone.rb:783:in `initialize': Invalid argument - connect(2) for "fd12:3456:789a:1::1" port 5985 (Errno::EINVAL)
	from /home/troyready/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.3/lib/chef/knife/vsphere_vm_clone.rb:783:in `new'
	from /home/troyready/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.3/lib/chef/knife/vsphere_vm_clone.rb:783:in `tcp_test_winrm'
	from /home/troyready/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.3/lib/chef/knife/vsphere_vm_clone.rb:373:in `wait_for_access'
	from /home/troyready/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.3/lib/chef/knife/vsphere_vm_clone.rb:357:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:422:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:421:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:214:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:51:in `load'
	from /usr/bin/knife:51:in `<main>'
```

**Comment by tim95030** [comment]
I apologize I misread the code for knife-windows the fix to use transport to set the default value will only work in 1.0.0 and on. Which I tested and it isn't compatible with knife-vsphere as they moved some things. As such I will create a pull request that does this logic in this codebase.

**Comment by swalberg** [comment]
This should be fixed... If not, please let us know!
