### ISSUE TITLE
DHCP not working

### ISSUE THREAD

**Issue by ZedCode** [chef-partners/knife-vsphere#221]
Hi,

I am trying to clone a template using DHCP. This is the stack trace I'm seeing:
```
/Users/[my_user]/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.7/lib/chef/knife/base_vsphere_command.rb:211:in `find_pool': undefined method `split' for nil:NilClass (NoMethodError)
	from /Users/[my_user]/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.7/lib/chef/knife/vsphere_vm_clone.rb:471:in `generate_clone_spec'
	from /Users/[my_user]/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.7/lib/chef/knife/vsphere_vm_clone.rb:310:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:405:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:404:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:203:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:54:in `load'
	from /opt/chefdk/bin/knife:54:in `<main>'
```
The command I'm executing is:
```
% knife vsphere vm clone vm-000 \
      --folder 'Templates/CentOS' \
      --template centos67-template \
      --dest-folder testingVMs \
      --cvlan vlan[XXX] \
      --cgw [xx].[xx].[xx].1 \
      --chostname vm-000 \
      --cips dhcp \
      --cdnsips '[dns IP 1],[dns IP 2]' \
      --thin-provision \
      --start -VV
```
This works fine with static IPs. Because I saw issue 143 mentioned an issue similar to this I decided to play it safe and rebuild the gem from source, but am getting the same error.

Any ideas of what I might be doing wrong?

edit: this is the error without `-VV`:
```
ERROR: knife encountered an unexpected error
This may be a bug in the 'vsphere vm clone' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `split' for nil:NilClass
```

Thanks!
zc

**Comment by swalberg** [comment]
Hi Zed,

It looks like you need to pass a `--resource-pool` if you use `--thin-provision`. [see here](https://github.com/chef-partners/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_clone.rb#L470-L472)

That's quite likely a problem on our side, as the code before it goes to great lengths to find the appropriate pool if you don't add one. That code goes a while back so I'd have to do some research to say for sure, though.

Try dropping `--thin-provision`... Are you positive it was there when you tried with a static address?

**Comment by ZedCode** [comment]
Aha! My other datacenter has clusters, but the one I'm deploying these to does not. That would explain it. Works perfectly now.

Thanks Sean!!

**Comment by gravyflex** [comment]
Thanks!
