### ISSUE TITLE
knife vsphere clone error - Exception: NoMethodError: undefined method `ipAddress' for nil:NilClass

### ISSUE THREAD

**Issue by reddypramod85** [chef-partners/knife-vsphere#335]
### What are you trying to do and what's not working?
Trying to clone a VM from existing template in vSphere

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information
```
$ knife vsphere vm clone 'xxxx' --template 'xxx' --bootstrap --cips dhcp --ssh-user xxx--ssh-password xxxx  --bootstrap-proxy 'xxxxxxxx' --resource-pool 'xxxxx' --datastore 'xxxxx' --run-list 'xxxx' --node-name 'xxxx'
Cloning template xxx to new VM xxxx
Finished creating virtual machine xxx
Powered on virtual machine xxxx
Waiting for network interfaces to become available...
Found address 192.168.122.1
DEBUG: value for config item bootstrap_nic: 0
C:/Users/Administrator/AppData/Local/chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.23/lib/chef/knife/vsphere_vm_clone.rb:432:in `guest_address': undefined method `ipAddress' for nil:NilClass (NoMethodError)
        from C:/Users/Administrator/AppData/Local/chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.23/lib/chef/knife/vsphere_vm_clone.rb:384:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89-universal-mingw32/lib/chef/knife.rb:430:in `block in run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89-universal-mingw32/lib/chef/knife.rb:429:in `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89-universal-mingw32/lib/chef/knife.rb:219:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89-universal-mingw32/lib/chef/application/knife.rb:156:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89-universal-mingw32/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/bin/knife:68:in `load'
        from C:/opscode/chefdk/bin/knife:68:in `<main>'


```

### Other details, such as gem version and if you're working with a Linux or Windows VM

knife-vsphere-1.2.23 - RHEL VM

**Comment by swalberg** [comment]
Hi, thanks for the details. Does your template have multiple NICs in it? It's getting caught up in a place that looks for the first non link-local address but it doesn't seem to be an IP.

A few thoughts:

* Console in and do an `ifconfig` / `ip addr`
* Does `--bootstrap-ipv4` help? 
* If you have multiple NICs, `--bootstrap-nic 1` may also help.

**Comment by swalberg** [comment]
Closing some stale issues. If you still need help please feel free to re-open this, or start a new issue! Thanks.
