### ISSUE TITLE
Regression in 1.2.24:  

### ISSUE THREAD

**Issue by kozmikyak** [chef-partners/knife-vsphere#352]
### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information
```
[probs007@oit-provision-tools-01 chef-probs007-testing]$ gem list |grep knife-vsphere
knife-vsphere (1.2.23)
[probs007@oit-provision-tools-01 chef-probs007-testing]$ knife vsphere vm clone     "lptsand-probs007.oit.umn.edu"     -u "probs007"     -f "LNX"     --template "rhel7-template"     --ccpu "2"     --cdomain "oit.umn.edu"     --chostname "lptsand-probs007"     --cips ""dhcp""     --cmacs "02:51:0a:20:6e:a1"     --cram "2"     --sw-uuid "36 26 23 50 53 98 00 37 fc 59 4d b7 75 8d c4 11"     --cvlan "DC04-WG019_10.32.110.129-254_v957"     --datastorecluster "lnx-wb-sata-01"     --dest-folder "LNX"     --resource-pool "LNX"
Cloning template rhel7-template to new VM lptsand-probs007.oit.umn.edu



[probs007@oit-provision-tools-01 chef-probs007-testing]$ gem uninstall knife-vsphere -a
[probs007@oit-provision-tools-01 chef-probs007-testing]$ gem install knife-vsphere
Fetching: knife-vsphere-1.2.24.gem (100%)
Successfully installed knife-vsphere-1.2.24
1 gem installed
[probs007@oit-provision-tools-01 chef-probs007-testing]$ gem list |grep knife-vsphere
knife-vsphere (1.2.24)
[probs007@oit-provision-tools-01 chef-probs007-testing]$ knife vsphere vm clone     "lptsand-probs007.oit.umn.edu"     -u "probs007"     -f "LNX"     --template "rhel7-template"     --ccpu "2"     --cdomain "oit.umn.edu"     --chostname "lptsand-probs007"     --cips ""dhcp""     --cmacs "02:51:0a:20:6e:a1"     --cram "2"     --sw-uuid "36 26 23 50 53 98 00 37 fc 59 4d b7 75 8d c4 11"     --cvlan "DC04-WG019_10.32.110.129-254_v957"     --datastorecluster "lnx-wb-sata-01"     --dest-folder "LNX"     --resource-pool "LNX"
Enter your password:
ERROR: knife encountered an unexpected error
This may be a bug in the 'vsphere vm clone' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `name' for nil:NilClass



[probs007@oit-provision-tools-01 chef-probs007-testing]$ knife vsphere vm clone     "lptsand-probs007.oit.umn.edu"     -u "probs007"     -f "LNX"     --template "rhel7-template"     --ccpu "2"     --cdomain "oit.umn.edu"     --chostname "lptsand-probs007"     --cips ""dhcp""     --cmacs "02:51:0a:20:6e:a1"     --cram "2"     --sw-uuid "36 26 23 50 53 98 00 37 fc 59 4d b7 75 8d c4 11"     --cvlan "DC04-WG019_10.32.110.129-254_v957"     --datastorecluster "lnx-wb-sata-01"     --dest-folder "LNX"     --resource-pool "LNX" -VV
INFO: Using configuration from /home/probs007/orgs/chef-probs007-testing/.chef/knife.rb
DEBUG: value for config item datastore:
DEBUG: value for config item customization_macs: 02:51:0a:20:6e:a1
DEBUG: value for config item customization_ips: dhcp
DEBUG: value for config item chef_node_name:
DEBUG: value for config item vsphere_host: vc-prd.oit.umn.edu
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: probs007
DEBUG: value for config item vsphere_pass:
Enter your password:
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
DEBUG: value for config item vsphere_dc: UMNTC
DEBUG: value for config item folder: LNX
DEBUG: value for config item vsphere_dc: UMNTC
DEBUG: value for config item linked_clone:
DEBUG: value for config item host:
DEBUG: value for config item resource_pool: LNX
DEBUG: value for config item resource_pool: LNX
DEBUG: value for config item vsphere_dc: UMNTC
DEBUG: value for config item linked_clone:
DEBUG: value for config item datastore:
DEBUG: value for config item datastorecluster: lnx-wb-sata-01
DEBUG: value for config item datastorecluster: lnx-wb-sata-01
DEBUG: value for config item vsphere_dc: UMNTC
DEBUG: value for config item thin_provision:
DEBUG: value for config item mark_as_template:
DEBUG: value for config item annotation:
DEBUG: value for config item customization_cpucount: 2
DEBUG: value for config item customization_cpucount: 2
DEBUG: value for config item customization_memory: 2
DEBUG: value for config item customization_memory: 2
DEBUG: value for config item customization_macs: 02:51:0a:20:6e:a1
DEBUG: value for config item customization_macs: 02:51:0a:20:6e:a1
DEBUG: value for config item customization_sw_uuid: 36 26 23 50 53 98 00 37 fc 59 4d b7 75 8d c4 11
DEBUG: value for config item customization_vlan: DC04-WG019_10.32.110.129-254_v957
DEBUG: value for config item customization_sw_uuid: 36 26 23 50 53 98 00 37 fc 59 4d b7 75 8d c4 11
DEBUG: value for config item customization_sw_uuid: 36 26 23 50 53 98 00 37 fc 59 4d b7 75 8d c4 11
DEBUG: value for config item customization_vlan: DC04-WG019_10.32.110.129-254_v957
DEBUG: value for config item customization_vlan: DC04-WG019_10.32.110.129-254_v957
DEBUG: value for config item customization_sw_uuid: 36 26 23 50 53 98 00 37 fc 59 4d b7 75 8d c4 11
DEBUG: value for config item vsphere_dc: UMNTC
DEBUG: value for config item customization_sw_uuid: 36 26 23 50 53 98 00 37 fc 59 4d b7 75 8d c4 11
/home/probs007/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.24/lib/chef/knife/vsphere_vm_clone.rb:620:in `rescue in block in generate_clone_spec': undefined method `name' for nil:NilClass (NoMethodError)
	from /home/probs007/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.24/lib/chef/knife/vsphere_vm_clone.rb:607:in `block in generate_clone_spec'
	from /home/probs007/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.24/lib/chef/knife/vsphere_vm_clone.rb:605:in `each'
	from /home/probs007/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.24/lib/chef/knife/vsphere_vm_clone.rb:605:in `each_with_index'
	from /home/probs007/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.24/lib/chef/knife/vsphere_vm_clone.rb:605:in `generate_clone_spec'
	from /home/probs007/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.24/lib/chef/knife/vsphere_vm_clone.rb:355:in `run'
	from /home/probs007/.chefdk/gem/ruby/2.3.0/gems/chef-12.18.31/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
	from /home/probs007/.chefdk/gem/ruby/2.3.0/gems/chef-12.18.31/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /home/probs007/.chefdk/gem/ruby/2.3.0/gems/chef-12.18.31/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
	from /home/probs007/.chefdk/gem/ruby/2.3.0/gems/chef-12.18.31/lib/chef/knife.rb:219:in `run'
	from /home/probs007/.chefdk/gem/ruby/2.3.0/gems/chef-12.18.31/lib/chef/application/knife.rb:156:in `run'
	from /home/probs007/.chefdk/gem/ruby/2.3.0/gems/chef-12.18.31/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:57:in `load'
	from /opt/chefdk/bin/knife:57:in `<main>'
```

### Other details, such as gem version and if you're working with a Linux or Windows VM

The regression happened between 1.2.23 and 1.2.24, as shown by the above commands.  It is a Linux VM from template.

Seems like the name of some parameter "name" it's looking for has changed, whether this is a variable in a hash or a command line parameter or something I don't know.

**Comment by swalberg** [comment]
Hi, thanks for the bug report. My first guess is that this was caused by https://github.com/chef-partners/knife-vsphere/commit/cc2c839aad993cef9058afecd1441066284e09b8. I'll need to dig a bit further.

**Comment by kozmikyak** [comment]
I have some ideas . . .

```
    if get_config(:customization_vlan)
      vlan_list = get_config(:customization_vlan).split(',')
      sw_uuid   = get_config(:customization_sw_uuid)
      networks  = vlan_list.map { |vlan| find_network(vlan, sw_uuid) }

      cards = src_config.hardware.device.grep(RbVmomi::VIM::VirtualEthernetCard)

      networks.each_with_index do |network, index|
        card = cards[index] || abort("Can't find source network card to customize for vlan #{vlan_list[index]}")
        begin
          if get_config(:customization_sw_uuid) && (swuuid_list[index] != 'auto')
            switch_port = RbVmomi::VIM.DistributedVirtualSwitchPortConnection(
              switchUuid: swuuid_list[index], portgroupKey: network.key
            )
          else
            switch_port = RbVmomi::VIM.DistributedVirtualSwitchPortConnection(
              switchUuid: network.config.distributedVirtualSwitch.uuid, portgroupKey: network.key
            )
          end
          card.backing.port = switch_port
        rescue
          # not connected to a distibuted switch?
          card.backing = RbVmomi::VIM::VirtualEthernetCardNetworkBackingInfo(network: network, deviceName: network.name)
        end
        card.macAddress = mac_list[index] if get_config(:customization_macs) && mac_list[index] != AUTO_MAC
        dev_spec = RbVmomi::VIM.VirtualDeviceConfigSpec(device: card, operation: 'edit')
        clone_spec.config.deviceChange.push dev_spec
      end
    end
```

The lines that get "sw_uuid" and "networks" are new/modified.  Line 620 tries to get the "name" field of the "network" object, which is a single item from the "networks" list.  It seems to be the "card.backing =" line that looks for network.name.  The "network" object is therefore nil.

Filtering on VLAN name was added in the commit you mentioned, around Feb 1.  In that code there's a "map" command used to construct a list.  Maybe items that don't match are getting set to nil.

Maybe not--that's just a bird's eye reading.

In the meantime we can pin to 1.2.23 without issues at my site.

**Comment by kozmikyak** [comment]
I'm open to fixing my code that uses this, if I need to specify more/less information about the clone at the command line, though--if it's not really a regression in knife-vsphere, but rather functionality change, I can work with that.

**Comment by swalberg** [comment]
You're right, I think the problem is up top:

```
vlan_list = get_config(:customization_vlan).split(',')
sw_uuid   = get_config(:customization_sw_uuid)
networks  = vlan_list.map { |vlan| find_network(vlan, sw_uuid) }
```

The `map` takes the list of VLANS and UUIDs, and returns an array of the corresponding network objects. I think the problem is we're making double use of `customization_sw_uuid`, so it's trying to find the VLANs with that particular UUID.

https://github.com/chef-partners/knife-vsphere/pull/336#discussion_r95494080 is some conversation that touches on it.
