### ISSUE TITLE
Network List for VM not working

### ISSUE THREAD

**Issue by jirah** [chef-partners/knife-vsphere#367]
### Versions:
* Version of knife-vsphere: 1.2.26
* Chef Development Kit Version: 1.3.43

### Platform Details

* Version of vSphere: No idea.
* Version of ESXi: 5.5

### Scenario:
List Networks on a VM.

### Expected Result:
List of the Network the VM currently has

### Actual Result:
An error, as follows:
```
[root@workstation ~]# knife vsphere vm network list docker-engine -VV
INFO: Using configuration from /root/.chef/knife.rb
DEBUG: value for config item vsphere_host: vcenter.services.asdf.com
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl: 
DEBUG: value for config item vsphere_user: vcenter@vsphere.local
DEBUG: value for config item vsphere_pass: adgasdfasfwer
DEBUG: value for config item vsphere_pass: adgasdfasfwer
DEBUG: value for config item vsphere_pass: adgasdfasfwer
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host: 
DEBUG: value for config item proxy_port: 
DEBUG: value for config item vsphere_dc: DC1
DEBUG: value for config item folder: 
DEBUG: value for config item vsphere_dc: DC1
/root/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.26/lib/chef/knife/vsphere_vm_network_list.rb:31:in `block (2 levels) in run': undefined method `port' for #<RbVmomi::VIM::VirtualEthernetCardNetworkBackingInfo:0x000000061079c0> (NoMethodError)
	from /root/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.26/lib/chef/knife/vsphere_vm_network_list.rb:30:in `each'
	from /root/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.26/lib/chef/knife/vsphere_vm_network_list.rb:30:in `each'
	from /root/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.26/lib/chef/knife/vsphere_vm_network_list.rb:30:in `grep'
	from /root/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.26/lib/chef/knife/vsphere_vm_network_list.rb:30:in `block in run'
	from /root/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.26/lib/chef/knife/vsphere_vm_network_list.rb:29:in `map'
	from /root/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.26/lib/chef/knife/vsphere_vm_network_list.rb:29:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/knife.rb:219:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/knife.rb:156:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:58:in `load'
	from /opt/chefdk/bin/knife:58:in `<main>'
```

**Comment by swalberg** [comment]
Hi, is this on a distributed switch? The networks I get back are of class `VirtualEthernetCardDistributedVirtualPortBackingInfo`.

**Comment by swalberg** [comment]
Closing some stale issues. If you still need help please feel free to re-open this, or start a new issue! Thanks.
