### ISSUE TITLE
Cloning a Windows VM fails

### ISSUE THREAD

**Issue by talcloudshare** [chef-partners/knife-vsphere#368]
### Versions:

* Version of knife-vsphere: 1.2.26
* Version of chef: 12.17.44

### Platform Details

* Version of vSphere: 6.5.0 Build 4602587
* Version of ESXi:

### Scenario:

Trying to clone a Windows VM from template, using customization specification. Plugin tries to invoke a method on a nil object and cloning fails.

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information:

```
$ knife vsphere vm clone **** --vsdc **** --vshost **** --vsinsecure true --vsuser **** --vspass **** --datastore **** --resource-pool **** --dest-folder **** --folder **** --template **** --cspec knife-vsphere-plugin --ccpu 1 --cram 1 --cdomain **** --cgw **** --cdnsips **** --cdnssuffix **** --chostname **** --cvlan **** --cips **** --cmacs auto --sw-uuid auto --bootstrap --environment **** --bootstrap-version **** --run-list **** --node-name **** -VV
```

### Expected Result:

VM cloned

### Actual Result:

```
INFO: Using configuration from /home/sysadmin/workspace/deploy-windows/.chef/knife.rb
DEBUG: value for config item datastore: ****
DEBUG: value for config item datastorecluster:
DEBUG: value for config item customization_macs: auto
DEBUG: value for config item chef_node_name: ****
DEBUG: value for config item vsphere_host: ****
DEBUG: value for config item vsphere_path: ****
DEBUG: value for config item vsphere_port: ****
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: ****
DEBUG: value for config item vsphere_pass: ****
DEBUG: value for config item vsphere_pass: ****
DEBUG: value for config item vsphere_pass: ****
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
DEBUG: value for config item vsphere_dc: ****
DEBUG: value for config item folder: ****
DEBUG: value for config item vsphere_dc: ****
DEBUG: value for config item linked_clone:
DEBUG: value for config item host:
DEBUG: value for config item resource_pool: ****
DEBUG: value for config item resource_pool: ****
DEBUG: value for config item vsphere_dc: ****
DEBUG: value for config item linked_clone:
DEBUG: value for config item datastore: ****
DEBUG: value for config item datastore: ****
DEBUG: value for config item vsphere_dc: ****
DEBUG: value for config item datastorecluster:
DEBUG: value for config item thin_provision:
DEBUG: value for config item mark_as_template:
DEBUG: value for config item annotation:
DEBUG: value for config item customization_cpucount: 1
DEBUG: value for config item customization_cpucount: 1
DEBUG: value for config item customization_corespersocket:
DEBUG: value for config item customization_memory: 1
DEBUG: value for config item customization_memory: 1
DEBUG: value for config item customization_memory_reservation:
DEBUG: value for config item customization_macs: auto
DEBUG: value for config item customization_ips: ****
DEBUG: value for config item customization_sw_uuid: auto
DEBUG: value for config item customization_vlan: ****
DEBUG: value for config item customization_sw_uuid: auto
DEBUG: value for config item customization_ips: ****
DEBUG: value for config item customization_vlan: ****
DEBUG: value for config item customization_vlan: ****
DEBUG: value for config item customization_sw_uuid: auto
DEBUG: value for config item vsphere_dc: ****
DEBUG: value for config item customization_sw_uuid: auto
DEBUG: value for config item customization_macs: auto
DEBUG: value for config item customization_spec: knife-vsphere-plugin
DEBUG: value for config item customization_spec: knife-vsphere-plugin
DEBUG: value for config item disable_customization: false
DEBUG: value for config item customization_dns_ips: ****
DEBUG: value for config item customization_dns_ips: ****
DEBUG: value for config item customization_dns_suffixes: ****
DEBUG: value for config item customization_dns_suffixes: ****
DEBUG: value for config item customization_gw: ****
DEBUG: Identified os as windows.
/home/sysadmin/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.26/lib/chef/knife/vsphere_vm_clone.rb:689:in `generate_clone_spec': undefined method `autoMode' for nil:NilClass (NoMethodError)
        from /home/sysadmin/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.26/lib/chef/knife/vsphere_vm_clone.rb:363:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/knife.rb:219:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/knife.rb:156:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/bin/knife:25:in `<top (required)>'
        from /opt/chefdk/bin/knife:58:in `load'
        from /opt/chefdk/bin/knife:58:in `<main>'
```

**Comment by jjasghar** [comment]
Can you run your command with `-VV` and post a gist of the output?

**Comment by talcloudshare** [comment]
Just did, sorry for the inconvenience

**Comment by swalberg** [comment]
Hi Tal, thanks for providing that information. The line you're running into,

` autoMode: cust_spec.identity.licenseFilePrintData.autoMode`

seems to be looking for some license data. With Windows this needs to be provided in your server cspec (`knife-vsphere-plugin` in your case) or a [plugin](https://github.com/chef-partners/knife-vsphere/wiki/Sample-plugin-to-do-unattended-Windows-installations).

There are so many options when creating a Windows box it's not practical to expose them all as command lines.

**Comment by talcloudshare** [comment]
Thanks, seems that ticking "Include Server License Information" in the vSphere customization specification wizard was all that was needed

**Comment by swalberg** [comment]
Glad to hear it's working, and thanks for providing the resolution.
