### ISSUE TITLE
error during knife vsphere vm clone using no customization 

### ISSUE THREAD

**Issue by dzabel** [chef-partners/knife-vsphere#387]
### Scenario:
```
knife vsphere vm clone newvm --template oldvm --folder "_Templates" --dest-folder="_Templates" --datastore vnx01_data10 --resource-pool 'VMCluster_Dev/Product Center - Infrastructure Service and Testing'
```
ERROR: RbVmomi::Fault: NicSettingMismatch: fault.NicSettingMismatch.summary

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information:
```
INFO: Using configuration from ~/.chef/knife.rb
DEBUG: value for config item datastore: vnx01_data10
DEBUG: value for config item datastorecluster:
DEBUG: value for config item customization_macs: auto
DEBUG: value for config item chef_node_name:
DEBUG: value for config item vsphere_host: xxxx
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: xxxx
DEBUG: value for config item vsphere_pass: xxxx
DEBUG: value for config item vsphere_pass: xxxx
DEBUG: value for config item vsphere_pass: xxxx
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
DEBUG: value for config item vsphere_dc: CMDataCenterHH
DEBUG: value for config item folder: _Templates
DEBUG: value for config item vsphere_dc: CMDataCenterHH
DEBUG: value for config item linked_clone:
DEBUG: value for config item host:
DEBUG: value for config item resource_pool: VMCluster_Dev/Product Center - Infrastructure Service and Testing
DEBUG: value for config item resource_pool: VMCluster_Dev/Product Center - Infrastructure Service and Testing
DEBUG: value for config item vsphere_dc: CMDataCenterHH
DEBUG: value for config item linked_clone:
DEBUG: value for config item datastore: vnx01_data10
DEBUG: value for config item datastore: vnx01_data10
DEBUG: value for config item vsphere_dc: CMDataCenterHH
DEBUG: value for config item datastorecluster:
DEBUG: value for config item thin_provision:
DEBUG: value for config item mark_as_template:
DEBUG: value for config item annotation:
DEBUG: value for config item customization_cpucount:
DEBUG: value for config item customization_corespersocket:
DEBUG: value for config item customization_memory:
DEBUG: value for config item customization_memory_reservation:
DEBUG: value for config item customization_macs: auto
DEBUG: value for config item customization_ips:
DEBUG: value for config item customization_sw_uuid:
DEBUG: value for config item customization_vlan:
DEBUG: value for config item customization_spec:
DEBUG: value for config item disable_customization: false
DEBUG: value for config item customization_dns_ips:
DEBUG: value for config item customization_dns_suffixes:
DEBUG: value for config item customization_domain:
DEBUG: Identified os as linux.
DEBUG: value for config item customization_domain:
DEBUG: value for config item customization_plugin:
DEBUG: value for config item vsphere_dc: CMDataCenterHH
Cloning template oldvm to new VM newvm
VirtualMachineCloneSpec(
  config: VirtualMachineConfigSpec( deviceChange: [] ),
  customization: CustomizationSpec(
    globalIPSettings: CustomizationGlobalIPSettings(  ),
    identity: CustomizationLinuxPrep(
      domain: "",
      hostName: CustomizationFixedName( name: "newvm" )
    )
  ),
  location: VirtualMachineRelocateSpec(
    datastore: Datastore("datastore-91"),
    pool: ResourcePool("resgroup-688")
  ),
  powerOn: false,
  template: false
)
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rbvmomi-1.9.4/lib/rbvmomi/vim/Task.rb:11:in `wait_for_completion': NicSettingMismatch: fault.NicSettingMismatch.summary (RbVmomi::Fault)
	from ~/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-2.0.0/lib/chef/knife/vsphere_vm_clone.rb:377:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/knife.rb:219:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/knife.rb:156:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:58:in `load'
	from /opt/chefdk/bin/knife:58:in `<main>'
```

System get cloned and seems to work, but exit code 100 and error is thrown as described.

**Comment by dzabel** [comment]
adding cspec to the above command and the error is gone

**Comment by dzabel** [comment]
found this:
https://github.com/chef-partners/knife-vsphere/issues/18

adding --disable-customization works for me and the error disappear.

I guess this should be set automatically, if no cspec is defined.

**Comment by swalberg** [comment]
Thanks for bringing this one up. It comes up every so often here and I'm sure more often elsewhere that doesn't go logged. I even got this error last week.

The error happens when the template has some number of NICs and the `CustomizationSpec` has a different number. Configuring the nic with a server side cspec and using `--cspec` is one way around it, though we also have options like `--cips` and `--cvlans` that let you do it on the command line (FWIW, at my job we don't use `--cspec`, it's all on the command line).

Your suggestion is interesting -- if we implicitly disabled customization when no customization options (basically `--c*`) were passed that might help some cases. By default, we always try to set a hostname in the `identity`. I wonder if that's behaviour that people rely on?

Thinking this through a bit more, I'm not sure that it would cover all cases. There are customization options that apply to things other than NICs, e.g. `--cdnsips`. So if someone requests we set the DNS server but doesn't otherwise configure the NICs, we're going to hit this exception because we can't disable customization.

I think the first step would be to catch the specific exception and give a good error message that lays out the options (probably by pointing the user to a section of the README or a Wiki page). Then we could decide if there are good times to not customize at all based on which options were passed. What do you think about that?
