### ISSUE TITLE
knife vsphere vm delete doesn't release the IP

### ISSUE THREAD

**Issue by imlocn123** [chef-partners/knife-vsphere#392]
### Versions:

* Version of knife-vsphere:
* Version of chef:  Chef Development Kit Version: 1.2.22
                             chef-client version: 12.18.31

### Platform Details

* Version of vSphere:  6.5.0
* Version of ESXi: ESXi 3

### Scenario:
I am trying to delete and clone VM using the same static IP address; however , the IP address is not released 

### Please paste the command and output (run with `-VV`). 
```
knife vsphere vm delete -VV host50 -f XXX_DEV --purge --vshost my-vcenter.nacr.com
INFO: Using configuration from C:/Users/yyyy/.chef/knife.rb                                                                                                    
DEBUG: value for config item vsphere_host: onguard-vcenter.nacr.com                                                                                               
DEBUG: value for config item vsphere_path: /sdk                                                                                                                   
DEBUG: value for config item vsphere_port: 443                                                                                                                    
DEBUG: value for config item vsphere_nossl:                                                                                                                       
DEBUG: value for config item vsphere_user: yyyy                                                                                                                
DEBUG: value for config item vsphere_pass: xxxx                                                                                                             
DEBUG: value for config item vsphere_pass: xxxx                                                                                                             
DEBUG: value for config item vsphere_pass: xxxx                                                                                                             
DEBUG: value for config item vsphere_insecure: true                                                                                                               
DEBUG: value for config item proxy_host:                                                                                                                          
DEBUG: value for config item proxy_port:                                                                                                                          
DEBUG: value for config item folder: XXX_DEV                                                                                                                      
DEBUG: value for config item vsphere_dc: Onguard Datacenter                                                                                                       
Deleted virtual machine host50                                                                                                                                     
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request                                                                                                    
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request                                                                                                   
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request                                                                                                
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request                                                                                                 
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request                                                                                                
DEBUG: Signing the request as yyyy                                                                                                                             
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request                                                                                              
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request                                                                                        
DEBUG: Initiating GET to https://XXXX/organizations/xxxx/nodes/host50                                                                     
DEBUG: ---- HTTP Request Header Data: ----                                                                                                                        
DEBUG: Accept: application/json                                                                                                                                   
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3                                                                                                   
DEBUG: X-Ops-Server-API-Version: 1                                                                                                                                
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;                                                                                                                    
DEBUG: X-OPS-USERID: yyyy                                                                                                                                      
DEBUG: X-OPS-TIMESTAMP: 2017-08-21T15:50:21Z                                                                                                                      
DEBUG: X-OPS-CONTENT-HASH: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=                                                                                                           
DEBUG: X-OPS-AUTHORIZATION-1: VKTq8ABsKOaB/VHw7PPY1XmcoWHN2xVNnVDOQD6zBRBuFkoHQnDAqMuIFPll                                                                        
DEBUG: X-OPS-AUTHORIZATION-2: 3utr80RRbIrF7IR1dG6AizEupt/xB8Mp+z53R5JkzpbKJ+DhxtE25Kl4qQNL                                                                        
DEBUG: X-OPS-AUTHORIZATION-3: VluyWBZJnP/mh1SBa5KCHF0NW+EY+Jp+NvK10UwFW5NBlXLqmqiOKveKkaPr                                                                        
DEBUG: X-OPS-AUTHORIZATION-4: QQiPfA21yD0NCs6mB8Y1tICGGCmxdTJPAiXzfPe2pUQe0eoE0cDn0/v8DGo9                                                                        
DEBUG: X-OPS-AUTHORIZATION-5: 5C4u2897NJfRKsfVaIYcfSPoE3MmuslJ/aIIeLncnpY9PLXhBBMjFIBHWjhs                                                                        
DEBUG: X-OPS-AUTHORIZATION-6: MSzz2f2ETryUy2+IxmafVKI7s4xEu8Ji8gN87t8oLw==                                                                                        
DEBUG: HOST: abc.edf.com:443                                                                                                                     
DEBUG: X-REMOTE-REQUEST-ID: 4dbbc1bf-d9fc-460c-a1cf-22f744525af4                                                                                                  
DEBUG: ---- End HTTP Request Header Data ----                                                                                                                     
DEBUG: ---- HTTP Status and Header Data: ----                                                                                                                     
DEBUG: HTTP 1.1 404 Object Not Found                                                                                                                              
DEBUG: server: ngx_openresty/1.4.3.6                                                                                                                              
DEBUG: date: Mon, 21 Aug 2017 15:50:22 GMT                                                                                                                        
DEBUG: content-length: 36                                                                                                                                         
DEBUG: connection: close                                                                                                                                          
DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=1.4.0                                                                                                   
DEBUG: ---- End HTTP Status/Header Data ----                                                                                                                      
DEBUG: ---- HTTP Response Body ----                                                                                                                               
DEBUG: {"error":["node 'host50' not found"]}                                                                                                                       
DEBUG: ---- End HTTP Response Body -----                                                                                                                          
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response                                                                                       
DEBUG: Content-Length validated correctly.                                                                                                                        
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response                                                                                             
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response                                                                                               
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response                                                                                                
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response                                                                                               
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response                                                                                                  
DEBUG: Expected JSON response, but got content-type ''                                                                                                            
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response                                                                                                   
INFO: HTTP Request Returned 404 Object Not Found: error                                                                                                           
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/net/http/response.rb:120:in `error!': 404 "Object Not Found" (Net::HTTPServerException)                                 
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/http.rb:150:in `request'                                
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/http.rb:115:in `get'                                    
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/node.rb:581:in `load'                                   
        from C:/Users/yyyy/AppData/Local/chefdk/gem/ruby/2.3.0/gems/knife-vsphere-2.0.0/lib/chef/knife/vsphere_vm_delete.rb:42:in `destroy_item'               
        from C:/Users/yyyy/AppData/Local/chefdk/gem/ruby/2.3.0/gems/knife-vsphere-2.0.0/lib/chef/knife/vsphere_vm_delete.rb:71:in `run'                        
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'   
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'          
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'            
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/knife.rb:219:in `run'                                   
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application/knife.rb:156:in `run'                       
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/bin/knife:25:in `<top (required)>'                               
        from C:/opscode/chefdk/bin/knife:68:in `load'                                                                                                             
        from C:/opscode/chefdk/bin/knife:68:in `<main>'      

```
                                                                                                     
### Expected Result:
Expect IP is released so I can re-clone the same VM again

### Actual Result:
From the vSphere Web Client, I see the host50 was deleted; however when I try to clone the same VM again,  IP didn't release from the delete VM , therefore the nclone VM doesn't have the same static IP.

Also, I notice the error:
 {"error":["node 'host50' not found"]}

After running delete VM, do we have to run the command:
knife vsphere vm network delete VMNAME NICNAME

What are the actual sequences when we run the delete VM?

**Comment by swalberg** [comment]
Hi, I'm not totally sure I understand this. I think the error you're getting is saying that the `host50` node doesn't exist on the Chef server. If your node is called something different you can pass the `-N` flag with the name of the VM in Chef, or omit the `--purge` option so it just deletes the VM and doesn't talk to Chef at all.

IP -wise I don't expect that deleting the VM will release any IPs. All this command does is send an instruction to VMWare to delete the VM and, optionally, delete the node and client from Chef (that's the `--purge` flag)

**Comment by imlocn123** [comment]
I think I found the problem. It would take the VMWare more than 1 minute to release the IP address. So I have to wait for more than 1 minute before I can run the clone VM again.

Another issue I see is when running the "knfie vsphere vm delete VMNAME  -f DEV_XXX --purge --vhost myvhost-vcenter.com" I see the error:
**_ERROR: The object you are looking for could not be found
Response: node 'OEP225' not found_**

How do I get rid of this error?

**Comment by swalberg** [comment]
Is that node in Chef? `knife node show OEP225`? When you use the `--purge` option, this gem will call Chef to ask it to remove the client and node records.

We store VMs by short name and Chef nodes by fqdn so when I use this command I normally do something like `knife vsphere vm delete myvm --purge -N myvm.example.com`

**Comment by imlocn123** [comment]
Which command can I use to list the Chef node associated with the VM short name?.

**Comment by swalberg** [comment]
Try `knife node list | grep SHORTNAME` and see what pops up.

**Comment by imlocn123** [comment]
I run "knife node list" and couldn't find any Chef node associated with the VM short name

**Comment by swalberg** [comment]
Was the node ever registered with Chef? It's quite possible to have a VM that never used Chef in which case you don't need the `--purge` option and that error will go away.

Despite this gem being a `knife` plugin most of the functions talk directly to vSphere. It's only the deletion and creation of VMs that needs to talk to Chef (and only if it's a Chef managed node)

**Comment by imlocn123** [comment]
If I take out the --purge then this is the error I got:
"Corresponding node and client for the Host225 server were not deleted and remain registered with the Chef Server."

Could we have the "knife vsphere vm list" also display the node name

**Comment by swalberg** [comment]
Ah, I see... That message is misleading. It doesn't know if it's registered or not. It's just assuming that since you didn't ask to purge, it must still be registered.

vsphere doesn't have the information necessary to get the node name from Chef. I don't know of a way to link the two. We do it by convention. The node's short name is the name of the VM and the FQDN is in Chef.

**Comment by imlocn123** [comment]
when we use the knife vsphere vm clone --node-name MyNodeName so that when I delete VM with  --purge -N MyNodeName it should not error; however, I still see the error:
"ERROR: The object you are looking for could not be found
Response: node 'MyNodeName' not found"

**Comment by swalberg** [comment]
When you cloned the VM, did you also have `--bootstrap`? If not, you'll get a VM that's not in Chef, and you'll continue to get the error if you try to `--purge`.

It's helpful to think of the VM management and Chef as separate things.

**Comment by swalberg** [comment]
Closing some stale issues. If you still need help please feel free to re-open this, or start a new issue! Thanks.
