### ISSUE TITLE
Can clone command be made idempotent?

### ISSUE THREAD

**Issue by Ryuzavi** [chef-partners/knife-vsphere#416]
### Versions:
* Version of knife-vsphere: 2.0.2
* Version of chef: 13.6.4

### Platform Details

* Version of vSphere: 6.0.0
* Version of ESXi: 6.0.0

### Scenario:

Looking to use knife vsphere in our CI I noticed that the clone command would fail after the first clone with `ERROR: RbVmomi::Fault: DuplicateName: The name 'qa-knife-test' already exists`.

I was hoping the command would be idempotent and it would detect the environment already exists and then edits it if any changes \ moves straight to bootstrap.

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information:
```
knife vsphere vm clone qa-knife-test --template qa-template --bootstrap --cips dhcp -VV
INFO: Using configuration from C:/Users/test-user/chef/knife.rb
INFO: Started chef-zero at chefzero://localhost:1 with repository at .
  One version per cookbook
  cookbooks at C:/Users/test-user/chef/cookbooks
  data_bags at C:/Users/test-user/chef/data_bags
  environments at C:/Users/test-user/chef/environments
  roles at C:/Users/test-user/chef/roles
  clients at C:/Users/test-user/chef/clients
  nodes at C:/Users/test-user/chef/nodes
  users at C:/Users/test-user/chef/users
  acls at C:/Users/test-user/chef/acls
  containers at C:/Users/test-user/chef/containers
  groups at C:/Users/test-user/chef/groups
  cookbook_artifacts at C:/Users/test-user/chef/cookbook_artifacts
  policies at C:/Users/test-user/chef/policies
  policy_groups at C:/Users/test-user/chef/policy_groups
  client_keys at C:/Users/test-user/chef/client_keys

DEBUG: value for config item datastore:
DEBUG: value for config item customization_macs: auto
DEBUG: value for config item chef_node_name:
DEBUG: value for config item vsphere_host: ***
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: ***
DEBUG: value for config item vsphere_pass: ***
DEBUG: value for config item vsphere_pass: ***
DEBUG: value for config item vsphere_pass: ***
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
DEBUG: value for config item vsphere_dc: ***
DEBUG: value for config item folder:
DEBUG: value for config item vsphere_dc: ***
DEBUG: value for config item linked_clone:
DEBUG: value for config item host:
DEBUG: value for config item resource_pool:
DEBUG: value for config item vsphere_dc: ***
DEBUG: value for config item datastore:
DEBUG: value for config item datastorecluster:
DEBUG: value for config item customization_vlan:
DEBUG: value for config item linked_clone:
DEBUG: value for config item datastore:
DEBUG: value for config item datastorecluster:
DEBUG: value for config item thin_provision:
DEBUG: value for config item mark_as_template:
DEBUG: value for config item annotation:
DEBUG: value for config item customization_cpucount:
DEBUG: value for config item customization_corespersocket:
DEBUG: value for config item customization_memory:
DEBUG: value for config item customization_memory_reservation:
DEBUG: value for config item customization_macs: auto
DEBUG: value for config item customization_ips: dhcp
DEBUG: value for config item customization_sw_uuid:
DEBUG: value for config item customization_vlan:
DEBUG: value for config item customization_spec:
DEBUG: value for config item disable_customization: false
DEBUG: value for config item customization_dns_ips:
DEBUG: value for config item customization_dns_suffixes:
DEBUG: value for config item customization_gw:
DEBUG: value for config item customization_domain:
DEBUG: Identified os as linux.
DEBUG: value for config item customization_domain:
DEBUG: value for config item customization_plugin:
DEBUG: value for config item folder:
DEBUG: value for config item vsphere_dc: ***
Cloning template qa-template to new VM qa-knife-test
VirtualMachineCloneSpec(
  config: VirtualMachineConfigSpec( deviceChange: [] ),
  customization: CustomizationSpec(
    globalIPSettings: CustomizationGlobalIPSettings(  ),
    identity: CustomizationLinuxPrep(
      domain: "",
      hostName: CustomizationFixedName( name: "qa-knife-test" )
    ),
    nicSettingMap: [CustomizationAdapterMapping(
       adapter: CustomizationIPSettings( ip: CustomizationDhcpIpGenerator(  ) )
     )]
  ),
  location: VirtualMachineRelocateSpec( pool: ResourcePool("resgroup-937") ),
  powerOn: false,
  template: false
)
C:/Users/test-user/AppData/Local/chefdk/gem/ruby/2.4.0/gems/rbvmomi-1.11.6/lib/rbvmomi/vim/Task.rb:14:in `wait_for_completion': DuplicateName: The name 'qa-knife-test' already exists. (RbVmomi::Fault)
        from C:/Users/test-user/AppData/Local/chefdk/gem/ruby/2.4.0/gems/knife-vsphere-2.0.2/lib/chef/knife/vsphere_vm_clone.rb:380:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4-universal-mingw32/lib/chef/knife.rb:442:in `block in run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4-universal-mingw32/lib/chef/knife.rb:441:in `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4-universal-mingw32/lib/chef/knife.rb:219:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4-universal-mingw32/lib/chef/application/knife.rb:156:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4-universal-mingw32/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/bin/knife:267:in `load'
        from C:/opscode/chefdk/bin/knife:267:in `<main>'
```

### Expected Result:
Well I was hoping it would detect that the VM already exists and moves to bootstrap.

### Actual Result:
It failed with `ERROR: RbVmomi::Fault: DuplicateName: The name 'qa-knife-test' already exists`

**Comment by swalberg** [comment]
Hi, I've run into this myself often and idempotency would have helped. Would need to think this one through as there might be cases where the clone succeeded but something else went wrong such that we have a VM that has not finished customization or is otherwise unsuitable for bootstrapping.

If it helps, most of our options are identical to those of `knife bootstrap`. If I mess something up (like typoing the runlist) I just run `knife bootstrap ......` rather than wipe and clone the VM again.

**Comment by Ryuzavi** [comment]
Swift reply :)  Looking at other tools out there like Ansible and the chef-provisioning-vsphere gem, they seem to have implementations for this as a reference perhaps ([although ansible's seems to be broken at the moment! ](https://github.com/ansible/ansible/issues/23663).

I'm looking to automate this so some logic to switch to config change and then bootstrap would be the approach I suppose.  Will play around.  Cheers.

**Comment by swalberg** [comment]
Looking at the code I think we just need to catch that `DuplicateName` exception from the `CloneVM_Task` and continue on rather than raise/exit.

**Comment by swalberg** [comment]
So I ended up needing this earlier today and wrote the code. Thanks for the idea!
