### ISSUE TITLE
knife vsphere vm clone command creates its own vlan standard port group in vCenter, instead of joining the specified --cvlan distrubuted port group

### ISSUE THREAD

**Issue by Zorrom** [chef-partners/knife-vsphere#418]
### Versions:

* Version of knife-vsphere: 2.0.1
* Version of chef: 12.19.36

### Platform Details

* Version of vSphere: 6.5.0
* Version of ESXi: 6.5.0

### Scenario:
I am trying to spin a vm using the following command

knife vsphere vm clone testVM --dest-folder Chef_Test --template TEST_TMPT --start --cvlan vlan01 --datastore my_datastore --cspec winspec

The above command spins the vm with my customization template options but instead of joining the vlan01 Distributed Port Group(dvSwitch3), Chef creates a completely new vlan01 Standard Network Port Group for itself on the vCenter and adds the vm there.

So as means of this the VM is joined to a completely different Vlan that never existed in the vCenter itself. This causes the VM network adapter settings to stay disconnected and the network connections are failed in short.

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information:
[root@chefworkstation .chef]# knife vsphere vm clone testVM --dest-folder Chef_Test --template TEST_CHEF_TMPT --start --cvlan VLAN01 --datastore my_datastore --cspec Windows_spec -VV
Cloning template TEST_CHEF_TMPT to new VM testVM
VirtualMachineCloneSpec(
  config: VirtualMachineConfigSpec(
    deviceChange: [VirtualDeviceConfigSpec(
       device: VirtualE1000e(
         addressType: "assigned",
         backing: VirtualEthernetCardNetworkBackingInfo(
           deviceName: "VLAN01",
           network: DistributedVirtualPortgroup("dvportgroup-142")
         ),
         connectable: VirtualDeviceConnectInfo(
           allowGuestControl: true,
           connected: false,
           startConnected: true,
           status: "untried"
         ),
         controllerKey: 100,
         deviceInfo: Description(
           label: "Network adapter 1",
           summary: "my_PortGroup"
         ),
         key: 4000,
         macAddress: nil,
         resourceAllocation: VirtualEthernetCardResourceAllocation(
           limit: -1,
           reservation: 0,
           share: SharesInfo( level: "normal", shares: 50 )
         ),
         unitNumber: 7,
         uptCompatibilityEnabled: false,
         wakeOnLanEnabled: true
       ),
       operation: "edit"
     )]
  ),
  customization: CustomizationSpec(
    encryptionKey: [48,
     -126,
     4,
     26,
     48,
     -126,
     3,
     2,
     -96,
     3,
     2,
     1,
     2,
     2,
     9,
     0,
     -48,
     -78,
     -70,
     35,
     -38,
     26,
     -36,
     113,
     48,
     13,
     6,
     9,
     42,
     -122,
     72,
     -122,
     -9,
     13,
     1,
     1,
     11,
     5,
     0,
     48,
     -127,
     -101,
     49,
     11,
     48,
     9,
     6,
     3,
     85,
     4,
     3,
     12,
     2,
     67,
     65,
     49,
     22,
     48,
     20,
     6,
     10,
     9,
     -110,
     38,
     -119,
     -109,
     -14,
     44,
     100,
     1,
     25,
     22,
     6,
     117,
     115,
     102,
     101,
     100,
     50,
     49,
     25,
     48,
     23,
     6,
     10,
     9,
     -110,
     38,
     -119,
     -109,
     -14,
     44,
     100,
     1,
     25,
     22,
     9,
     97,
     103,
     105,
     46,
     108,
     111,
     99,
     97,
     108,
     49,
     11,
     48,
     9,
     6,
     3,
     85,
     4,
     6,
     19,
     2,
     85,
     83,
     49,
     19,
     48,
     17,
     6,
     3,
     85,
     4,
     8,
     12,
     10,
     67,
     97,
     108,
     105,
     102,
     111,
     114,
     110,
     105,
     97,
     49,
     38,
     48,
     36,
     6,
     3,
     85,
     4,
     10,
     12,
     29,
     98,
     103,
     99,
     50,
     117,
     115,
     45,
     112,
     115,
     99,
     102,
     101,
     100,
     48,
     50,
     46,
     101,
     117,
     49,
     46,
     49,
     99,
     111,
     114,
     112,
     46,
     111,
     114,
     103,
     49,
     15,
     48,
     13,
     6,
     3,
     85,
     4,
     11,
     12,
     6,
     86,
     77,
     119,
     97,
     114,
     101,
     48,
     30,
     23,
     13,
     49,
     54,
     48,
     56,
     51,
     49,
     49,
     53,
     49,
     55,
     52,
     55,
     90,
     23,
     13,
     50,
     54,
     48,
     56,
     50,
     54,
     49,
     53,
     48,
     57,
     50,
     52,
     90,
     48,
     -127,
     -126,
     49,
     13,
     48,
     11,
     6,
     3,
     85,
     4,
     3,
     12,
     4,
     118,
     112,
     120,
     100,
     49,
     22,
     48,
     20,
     6,
     10,
     9,
     -110,
     38,
     -119,
     -109,
     -14,
     44,
     100,
     1,
     25,
     22,
     6,
     117,
     115,
     102,
     101,
     100,
     50,
     49,
     25,
     48,
     23,
     6,
     10,
     9,
     -110,
     38,
     -119,
     -109,
     -14,
     44,
     100,
     1,
     25,
     22,
     9,
     97,
     103,
     105,
     46,
     108,
     111,
     99,
     97,
     108,
     49,
     11,
     48,
     9,
     6,
     3,
     85,
     4,
     6,
     19,
     2,
     85,
     83,
     49,
     49,
     48,
     47,
     6,
     3,
     85,
     4,
     11,
     12,
     40,
     109,
     73,
     68,
     45,
     48,
     48,
     55,
     56,
     51,
     56,
     52,
     48,
     45,
     56,
     99,
     50,
     49,
     45,
     52,
     102,
     101,
     56,
     45,
     97,
     55,
     101,
     100,
     45,
     57,
     50,
     54,
     49,
     97,
     50,
     56,
     57,
     48,
     97,
     50,
     56,
     48,
     -126,
     1,
     34,
     48,
     13,
     6,
     9,
     42,
     -122,
     72,
     -122,
     -9,
     13,
     1,
     1,
     1,
     5,
     0,
     3,
     -126,
     1,
     15,
     0,
     48,
     -126,
     1,
     10,
     2,
     -126,
     1,
     1,
     0,
     -78,
     19,
     -114,
     -27,
     7,
     -10,
     73,
     60,
     60,
     -105,
     54,
     89,
     -54,
     63,
     -63,
     -110,
     -81,
     58,
     -93,
     111,
     81,
     -24,
     -19,
     125,
     -102,
     -111,
     -99,
     92,
     -34,
     115,
     102,
     -115,
     50,
     -34,
     -44,
     90,
     -85,
     30,
     -28,
     -22,
     -26,
     -116,
     -91,
     -126,
     17,
     7,
     103,
     -66,
     36,
     -101,
     69,
     -45,
     72,
     62,
     74,
     -82,
     89,
     -77,
     -65,
     -85,
     -95,
     -14,
     12,
     -114,
     -47,
     37,
     -110,
     -102,
     9,
     -16,
     41,
     -123,
     118,
     -40,
     30,
     80,
     -79,
     73,
     6,
     -39,
     109,
     -8,
     44,
     -76,
     -50,
     76,
     -120,
     45,
     85,
     -16,
     57,
     -128,
     -79,
     47,
     31,
     -69,
     -47,
     -125,
     -49,
     -84,
     11,
     63,
     -16,
     -50,
     -79,
     29,
     -76,
     39,
     76,
     0,
     -94,
     -8,
     -35,
     77,
     -18,
     33,
     -39,
     -106,
     -94,
     26,
     13,
     -16,
     68,
     5,
     -40,
     -84,
     123,
     -101,
     -76,
     -96,
     99,
     -114,
     -7,
     126,
     9,
     -2,
     -56,
     21,
     -107,
     -118,
     48,
     68,
     -128,
     13,
     53,
     82,
     7,
     -125,
     -36,
     124,
     -113,
     37,
     19,
     103,
     -59,
     10,
     21,
     68,
     40,
     99,
     -98,
     -37,
     -17,
     121,
     66,
     -94,
     51,
     8,
     54,
     -47,
     -100,
     -118,
     -108,
     48,
     38,
     0,
     -3,
     -90,
     69,
     25,
     -10,
     6,
     107,
     124,
     23,
     86,
     -90,
     -83,
     -49,
     80,
     -117,
     32,
     117,
     -126,
     17,
     -61,
     -82,
     -36,
     59,
     126,
     -31,
     25,
     -113,
     95,
     99,
     -12,
     -87,
     -27,
     -88,
     -6,
     -115,
     95,
     24,
     -70,
     40,
     -99,
     -90,
     66,
     -67,
     86,
     -45,
     -106,
     -5,
     -5,
     -14,
     -37,
     -107,
     20,
     -16,
     46,
     50,
     120,
     -88,
     70,
     -75,
     80,
     -72,
     15,
     -28,
     99,
     57,
     -110,
     -118,
     -51,
     -34,
     91,
     103,
     -127,
     -67,
     -44,
     -11,
     -17,
     65,
     -64,
     59,
     -55,
     2,
     3,
     1,
     0,
     1,
     -93,
     120,
     48,
     118,
     48,
     11,
     6,
     3,
     85,
     29,
     15,
     4,
     4,
     3,
     2,
     5,
     -32,
     48,
     39,
     6,
     3,
     85,
     29,
     17,
     4,
     32,
     48,
     30,
     -126,
     28,
     98,
     103,
     99,
     50,
     117,
     115,
     45,
     118,
     99,
     102,
     101,
     100,
     48,
     50,
     46,
     101,
     117,
     49,
     46,
     49,
     99,
     111,
     114,
     112,
     46,
     111,
     114,
     103,
     48,
     29,
     6,
     3,
     85,
     29,
     14,
     4,
     22,
     4,
     20,
     -86,
     -96,
     -78,
     109,
     -48,
     99,
     74,
     74,
     43,
     -91,
     88,
     -84,
     -51,
     61,
     23,
     73,
     -109,
     -124,
     -46,
     -78,
     48,
     31,
     6,
     3,
     85,
     29,
     35,
     4,
     24,
     48,
     22,
     -128,
     20,
     116,
     92,
     -112,
     -105,
     112,
     40,
     19,
     -91,
     -37,
     73,
     -27,
     -88,
     80,
     -2,
     11,
     -39,
     71,
     22,
     -95,
     82,
     48,
     13,
     6,
     9,
     42,
     -122,
     72,
     -122,
     -9,
     13,
     1,
     1,
     11,
     5,
     0,
     3,
     -126,
     1,
     1,
     0,
     44,
     82,
     -63,
     79,
     -62,
     16,
     -17,
     -86,
     -99,
     -64,
     -4,
     -111,
     9,
     -80,
     71,
     80,
     -54,
     -54,
     -92,
     -34,
     -11,
     18,
     2,
     86,
     -27,
     83,
     -69,
     50,
     99,
     113,
     37,
     -71,
     -109,
     -59,
     -79,
     57,
     27,
     30,
     -35,
     96,
     -46,
     -104,
     -51,
     26,
     -11,
     -28,
     91,
     -38,
     -52,
     61,
     -35,
     -123,
     -16,
     28,
     121,
     -69,
     -3,
     -103,
     3,
     -17,
     -99,
     32,
     -117,
     80,
     4,
     38,
     -34,
     -53,
     -15,
     21,
     31,
     115,
     -15,
     -119,
     5,
     -31,
     -60,
     -94,
     23,
     57,
     -104,
     66,
     92,
     95,
     -26,
     -34,
     75,
     10,
     60,
     54,
     -43,
     21,
     80,
     -122,
     -8,
     -1,
     97,
     -21,
     -50,
     3,
     -118,
     -33,
     -50,
     -114,
     33,
     127,
     -116,
     -118,
     12,
     92,
     -123,
     -107,
     38,
     49,
     69,
     109,
     26,
     -118,
     -32,
     17,
     0,
     -3,
     70,
     -8,
     -52,
     58,
     -19,
     89,
     44,
     3,
     -110,
     34,
     32,
     97,
     50,
     106,
     45,
     -71,
     -127,
     20,
     -36,
     57,
     37,
     38,
     97,
     -38,
     -16,
     95,
     84,
     65,
     -60,
     8,
     -57,
     37,
     114,
     -17,
     84,
     9,
     -10,
     3,
     43,
     36,
     14,
     -33,
     119,
     27,
     -75,
     -92,
     98,
     -27,
     -43,
     -3,
     122,
     -116,
     95,
     0,
     38,
     70,
     -109,
     -49,
     -114,
     -32,
     -108,
     52,
     -76,
     98,
     -88,
     -73,
     -14,
     57,
     92,
     105,
     -3,
     121,
     -121,
     -47,
     -26,
     0,
     -41,
     -73,
     125,
     54,
     97,
     90,
     9,
     92,
     93,
     -97,
     -1,
     5,
     -4,
     -68,
     -49,
     -42,
     57,
     -17,
     -119,
     -123,
     -60,
     116,
     93,
     -48,
     29,
     3,
     -63,
     -50,
     112,
     33,
     -6,
     -88,
     -22,
     -92,
     -86,
     15,
     51,
     -23,
     5,
     -97,
     -87,
     -11,
     -28,
     70,
     64,
     41,
     -63,
     -53,
     -6,
     12,
     -22,
     -114,
     120,
     94,
     -68,
     -13,
     16,
     30],
    globalIPSettings: CustomizationGlobalIPSettings(
      dnsServerList: [],
      dnsSuffixList: []
    ),
    identity: CustomizationSysprep(
      guiRunOnce: CustomizationGuiRunOnce(
        commandList: ["net stop myservice",
         "reg delete my_reg_key"]
      ),
      guiUnattended: CustomizationGuiUnattended(
        autoLogon: true,
        autoLogonCount: 1,
        password: CustomizationPassword(
          plainText: false,
          value: "FwIuXmNRTmtXpgNlruE3UNi3MAO1Fz2yVKqEmSQwd/3buP6VbQZp3nAJZoxaFo9AoPgrB8LY4XEtAkUHQcQMkq6pdKRXtBX+WzMSrnnbWqFSL+54gd+gM3gAkYkqBEpD3/p99pB6pnaAvvGlEqRkZAR2T3PvWev5BKBFw2jfnMWAjuabi+ferV0t4BKxSD8/Ec5K8kncCjnBcOFMGD6OL7MRUDMeqkHhaD3wRlPtVd3MLPndX+jueqHkx5Qx3ICXOOJ50beGHhSJRkz6NVrnMCX5wO0HpM9izBrnjHpqMCEa2o30+9PA7XjY/G682uRyCpCne5YxROSqCvD6us8opA=="
        ),
        timeZone: 33
      ),
      identification: CustomizationIdentification( joinWorkgroup: "WORKGROUP"
      ),
      userData: CustomizationUserData(
        computerName: CustomizationVirtualMachineName(  ),
        fullName: "IT Department",
        orgName: "My Organization",
        productId: ""
      )
    ),
    nicSettingMap: [CustomizationAdapterMapping(
       adapter: CustomizationIPSettings(
         dnsServerList: ["10.*.*.1", "10.*.*.2"],
         gateway: ["10.*.*.3", "10.*.*.4"],
         ip: CustomizationFixedIp( ipAddress: "10.*.*.5" ),
         primaryWINS: "",
         secondaryWINS: "",
         subnetMask: "255.*.*.0"
       )
     )],
    options: CustomizationWinOptions( changeSID: true, deleteAccounts: false )
  ),
  location: VirtualMachineRelocateSpec(
    datastore: Datastore("datastore-121"),
    pool: ResourcePool("resgroup-8")
  ),
  powerOn: false,
  template: false
)
Finished creating virtual machine testVM
Powered on virtual machine testVM

### Expected Result:

Vm has to build with custom templates and get added to the distributed vlan passed using --cvlan

### Actual Result:

Vm builded but it creates its own VLAN instead of joining an existing one

**Comment by swalberg** [comment]
Since it's giving a `VirtualEthernetCardBackingInfo` I think we're hitting the block [here](https://github.com/chef-partners/knife-vsphere/blob/54dc42e26f162af0edabb0073a99375a5d761be3/lib/chef/knife/vsphere_vm_clone.rb#L657-L664). The code doesn't log anything and the `rescue` will catch anything, so this could be a variety of things.

Is the VLAN name correct? Is it on a distributed switch? Are there maybe multiple VLANs with that name?

If you can find `vsphere_vm_clone.rb` you could edit Line 662/663 from this:

```Ruby
   rescue
          # not connected to a distibuted switch?
```

to this:
```Ruby
  rescue Exception => e
     puts "Couldn't find backing info for the VLAN. I got #{e} instead"
```

that'll at least tell us why we're getting there.

**Comment by Zorrom** [comment]
Hi Sean,
     Let me see those changes and get back to you on this.

**Comment by Zorrom** [comment]
Hi Swal,

1. Yes the VLAN name is correct. I can see the exam vlan name as below when i the following command
knife vsphere vlan list
*
* # list of vlans
VLAN: VLAN01   # my vlan
*
*

2. Yes the vlan is on a ditributed switch which vlan01(dvSwitch3)
3. No there are no multiple vlans of the same vlan number

    I made the changes to the vpshere_vm_clone.rb and I got the following error when tried to run the vm clone command

No Title
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/knife-vsphere-2.0.1/lib/chef/knife/vsphere_vm_clone.rb:647:in `rescue in block in generate_clone_spec': uninitialized constant Chef::Knife::VsphereVmClone::Exception  (NameError)
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/knife-vsphere-2.0.1/lib/chef/knife/vsphere_vm_clone.rb:635:in `block in generate_clone_spec'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/knife-vsphere-2.0.1/lib/chef/knife/vsphere_vm_clone.rb:633:in `each'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/knife-vsphere-2.0.1/lib/chef/knife/vsphere_vm_clone.rb:633:in `each_with_index'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/knife-vsphere-2.0.1/lib/chef/knife/vsphere_vm_clone.rb:633:in `generate_clone_spec'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/knife-vsphere-2.0.1/lib/chef/knife/vsphere_vm_clone.rb:368:in `run'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/knife.rb:219:in `run'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/knife.rb:156:in `run'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/bin/knife:25:in `<top (required)>'
        from /bin/knife:57:in `load'
        from /bin/knife:57:in `<main>'

**Comment by swalberg** [comment]
That's weird. Maybe try `rescue => e` for that first line? I can try a couple of things when I get into work if that doesn't work out.

**Comment by Zorrom** [comment]
Our Infra is currently under a bit of maintenance kind of thing. So I couldnt check anything as of now. Will get back on this a bit later

**Comment by SandhyaBadgujar** [comment]
Hi I am trying the similar cmd for VM Clone and instead of changing the vlan a new vlan is getting created under dvSwitch3. Is the above issue resolved?

**Comment by swalberg** [comment]
Hi, not that I know of. I wasn't able to reproduce the problem. If you want to try adding that debugging output mentioned above, it might help me figure out why it's doing that.

**Comment by Zorrom** [comment]
Hi Sea,
    Sorry we got stuck with different objectives and so we have to put this on hold. So as per the error we found that our vCetner is designed in a way that everytime a Vlan is changed it would require MAC address to be passed with it which could either be manual or automatic. So specifying the Vlan without mac address is creating a completely different network group in the vCenter
    In the above command I passed the MAC address using --cmacs and specified my custom mac address along with vlan and this time the VM got allocated to the existing vLan that we have specified. However we got an error message during VM power on as follows

`RbVmomi::Fault: GenericVmConfigFault: Invalid VPX-assigned Ethernet address: 'my_mac_address_here'. `

To avoid this error we splitted the VM build operation and it was easy because we have an orchestrator doing all these steps.
1. Build VM without vlan and take the default vlan from the template
2. Delete the existing vlan
3. Add the vlan with the custom mac address
4. Fetch Ip of the machine and bootstrap with Chef - And these steps work just fine

So the error during power on is something coming from Chef or it's the vCenter issue.

**Comment by swalberg** [comment]
Thanks for the update. What you're seeing is coming from vsphere. I have a feeling that `--cmacs` option gets used for a couple of different things and you're in a corner case we didn't expect. 

Crazy idea here, does it work if you pick a MAC address outside the vmware OID? The only other occurrence of that error message I see in Google comes from a python project where that was one solution. This may be more for curiosity as I don't recommend using a made up MAC, but if it works, maybe I can figure out their eventual solution.

**Comment by Zorrom** [comment]
Not exactly. Once the machine is built , I am deleting the old network adapters and replacing them with a new network adapter. It was at this point I specify my VLAN along with my Mac address. This step works fine when the VLAN operation is carried out separately and only becomes a problem when passing both Mac and VLAN using knife vsphere command.
